"""Add the transaction created_at field

Revision ID: 709423d38222
Revises: 82fe1f193808
Create Date: 2024-09-05 17:57:07.342258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709423d38222'
down_revision = '82fe1f193808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
